inherit_from: .rubocop_todo.yml

Style/FrozenStringLiteralComment:
  Enabled: false
Documentation:
  Enabled: false
Naming/PredicateName:
  Enabled: false
Metrics/LineLength:
  Max: 100
Metrics/AbcSize:
  Max: 20